import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Sidebar from './components/Sidebar'
import Feed from './components/Feed'
import Widgets from './components/Widgets'
import { GetServerSideProps } from 'next'
import { fetchTweets } from '../utils/fetchTweets'
import { Tweet } from '../typings'

const inter = Inter({ subsets: ['latin'] })
interface Props{
  tweets:Tweet[]
}
export default function Home({tweets}:Props) {
  return (
    <div className='bg-gradient-to-l from-gray-300 to-white mx-auto max-h-screen overflow-hidden lg:min-w-6xl overflow-y-auto'>
      <Head>
        <title >Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter.ico" />
      </Head>
             
             <main className='grid grid-cols-9'>
              <Sidebar/>
              <Feed tweets={tweets}/>
              <Widgets/>
             </main>
    </div>
  )
}


export const getServerSideProps: GetServerSideProps = async (context)=>{
   const tweets = await fetchTweets()




   return {
    props:{
      tweets,
    }
   }
}